### ISSUE TITLE
Trained network type is private

### ISSUE THREAD

**Issue by benetis** [zenecture/neuroflow#3]
First, I would like to say - thank you for your work on this library

I am having trouble using types with trained network, because its returned type is: `DenseNetworkDouble`, which is a private type. So compiler can infer function type to be it, but I cannot specify it myself

**Comment by bogdanski** [comment]
hey, I just released version 1.6.8 with public types, since there is no real reason for private types here and I don't want to enforce generic functions or type-foo. :-)
Hope this helps.

Felix
